// <auto-generated />
using System;
using KrytenAssist.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrytenAssist.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KrytenAssistDbContext))]
    [Migration("20260718205146_AddCruiseAlertPersistence")]
    partial class AddCruiseAlertPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KrytenAssist.Core.Entities.PromptCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptCards");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTime")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("EventTimeUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseAlerts_EventKey");

                    b.HasIndex("EventTimeUtcTicks", "CreatedAtUtcTicks", "EventKey")
                        .HasDatabaseName("IX_CruiseAlerts_Newest");

                    b.HasIndex("Status", "Type", "EventTimeUtcTicks")
                        .HasDatabaseName("IX_CruiseAlerts_Status_Type_Event");

                    b.ToTable("CruiseAlerts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseAlerts_Duration", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseAlerts_EventKey", "length(\"EventKey\") = 64 AND \"EventKey\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseAlerts_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseAlerts_RetailSourceId_Length", "\"RetailSourceId\" IS NULL OR length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseAlerts_RetailSourceName_Length", "\"RetailSourceName\" IS NULL OR length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseAlerts_ShipName_Length", "length(\"ShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseAlerts_SourcePair", "(\"RetailSourceId\" IS NULL AND \"RetailSourceName\" IS NULL) OR (\"RetailSourceId\" IS NOT NULL AND \"RetailSourceName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruiseAlerts_Status", "\"Status\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_CruiseAlerts_Type", "\"Type\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_CruiseAlerts_TypeSource", "(\"Type\" IN (0, 1) AND \"RetailSourceId\" IS NOT NULL) OR (\"Type\" = 2 AND \"RetailSourceId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseAlertSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinimumPriceDropPercentage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PriceDropEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromotionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SavedCriteriaEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CruiseAlertSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseAlertSettings_Booleans", "\"PriceDropEnabled\" IN (0,1) AND \"PromotionEnabled\" IN (0,1) AND \"SavedCriteriaEnabled\" IN (0,1)");

                            t.HasCheckConstraint("CK_CruiseAlertSettings_Percentage", "CAST(\"MinimumPriceDropPercentage\" AS REAL) BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_CruiseAlertSettings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestEvidenceObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestProviderOfferId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestSourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "NormalizedShipName", "DepartureDate", "DurationNights", "RetailSourceId")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseHistories_Sailing_Source");

                    b.ToTable("CruiseHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseHistories_DurationNights", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseHistories_LatestProviderOfferId_Length", "length(\"LatestProviderOfferId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseHistories_LatestSourceReference_Length", "\"LatestSourceReference\" IS NULL OR length(\"LatestSourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseHistories_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseHistories_ShipName_Length", "length(\"NormalizedShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseHistories_SourceId_Length", "length(\"RetailSourceId\") <= 200");

                            t.HasCheckConstraint("CK_CruiseHistories_SourceName_Length", "\"RetailSourceName\" IS NULL OR length(\"RetailSourceName\") BETWEEN 1 AND 500");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItinerarySummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOfferId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CruiseHistoryId", "Fingerprint")
                        .HasDatabaseName("IX_CruiseObservations_History_Fingerprint");

                    b.HasIndex("CruiseHistoryId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseObservations_History_Sequence");

                    b.HasIndex("CruiseHistoryId", "ObservedAt", "Id")
                        .HasDatabaseName("IX_CruiseObservations_History_ObservedAt");

                    b.ToTable("CruiseObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseObservations_DeparturePort_Length", "\"DeparturePort\" IS NULL OR length(\"DeparturePort\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_DurationNights", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseObservations_Fingerprint_Length", "length(\"Fingerprint\") BETWEEN 1 AND 16000");

                            t.HasCheckConstraint("CK_CruiseObservations_ItinerarySummary_Length", "\"ItinerarySummary\" IS NULL OR length(\"ItinerarySummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_OperatorName_Length", "length(\"OperatorName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_PromotionSummary_Length", "\"PromotionSummary\" IS NULL OR length(\"PromotionSummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_ProviderOfferId_Length", "length(\"ProviderOfferId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseObservations_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_CruiseObservations_ShipName_Length", "length(\"ShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_Title_Length", "length(\"Title\") BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationPriceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Basis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CruiseObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseObservationId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseObservationPrices_Observation_Order");

                    b.ToTable("CruiseObservationPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseObservationPrices_Amount", "CAST(\"Amount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_Basis_Length", "\"Basis\" IS NULL OR length(\"Basis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_Currency", "length(\"Currency\") = 3 AND \"Currency\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_DisplayOrder", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceCabinEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cabin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Cabin")
                        .IsUnique()
                        .HasDatabaseName("UX_CruisePreferenceCabins_Profile_Cabin");

                    b.ToTable("CruisePreferenceCabins", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePreferenceCabins_Cabin", "\"Cabin\" BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceMonthEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Month")
                        .IsUnique()
                        .HasDatabaseName("UX_CruisePreferenceMonths_Profile_Month");

                    b.ToTable("CruisePreferenceMonths", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePreferenceMonths_Month", "\"Month\" BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaximumBudgetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximumBudgetBasis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaximumBudgetCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CruisePreferenceProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetAmount", "\"MaximumBudgetAmount\" IS NULL OR CAST(\"MaximumBudgetAmount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetBasis", "\"MaximumBudgetBasis\" IS NULL OR \"MaximumBudgetBasis\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetCurrency", "\"MaximumBudgetCurrency\" IS NULL OR (length(\"MaximumBudgetCurrency\") = 3 AND \"MaximumBudgetCurrency\" GLOB '[A-Z][A-Z][A-Z]')");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetTuple", "(\"MaximumBudgetAmount\" IS NULL AND \"MaximumBudgetCurrency\" IS NULL AND \"MaximumBudgetBasis\" IS NULL) OR (\"MaximumBudgetAmount\" IS NOT NULL AND \"MaximumBudgetCurrency\" IS NOT NULL AND \"MaximumBudgetBasis\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePriceDropAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentAmount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PercentageReduction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousAmount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reduction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruisePriceDropAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePriceDropDetails_Amounts", "CAST(\"PreviousAmount\" AS REAL) >= 0 AND CAST(\"CurrentAmount\" AS REAL) >= 0 AND CAST(\"Reduction\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_CurrentBasis_Length", "\"CurrentBasis\" IS NULL OR length(\"CurrentBasis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_CurrentCurrency", "length(\"CurrentCurrency\") = 3 AND \"CurrentCurrency\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_EvidenceKey_Length", "length(\"EvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_Percentage", "CAST(\"PercentageReduction\" AS REAL) BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_PreviousBasis_Length", "\"PreviousBasis\" IS NULL OR length(\"PreviousBasis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_PreviousCurrency", "length(\"PreviousCurrency\") = 3 AND \"PreviousCurrency\" GLOB '[A-Z][A-Z][A-Z]'");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePromotionAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruisePromotionAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePromotionDetails_CurrentSummary_Length", "length(\"CurrentSummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruisePromotionDetails_EvidenceKey_Length", "length(\"EvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruisePromotionDetails_PreviousSummary_Length", "\"PreviousSummary\" IS NULL OR length(\"PreviousSummary\") BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CabinPreferencesUnavailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfiguredBudgetAmount")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfiguredBudgetBasis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfiguredBudgetCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceTime")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedPriceAmount")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedPriceBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedPriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MonthConfiguredAndMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruiseSavedCriteriaAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Amounts", "(\"ConfiguredBudgetAmount\" IS NULL OR CAST(\"ConfiguredBudgetAmount\" AS REAL) >= 0) AND (\"MatchedPriceAmount\" IS NULL OR CAST(\"MatchedPriceAmount\" AS REAL) >= 0)");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Booleans", "\"MonthConfiguredAndMatched\" IN (0,1) AND \"CabinPreferencesUnavailable\" IN (0,1)");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_BudgetBasis", "\"ConfiguredBudgetBasis\" IS NULL OR \"ConfiguredBudgetBasis\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_BudgetTuple", "(\"ConfiguredBudgetAmount\" IS NULL AND \"ConfiguredBudgetCurrency\" IS NULL AND \"ConfiguredBudgetBasis\" IS NULL AND \"MatchedPriceAmount\" IS NULL AND \"MatchedPriceCurrency\" IS NULL AND \"MatchedPriceBasis\" IS NULL) OR (\"ConfiguredBudgetAmount\" IS NOT NULL AND \"ConfiguredBudgetCurrency\" IS NOT NULL AND \"ConfiguredBudgetBasis\" IS NOT NULL AND \"MatchedPriceAmount\" IS NOT NULL AND \"MatchedPriceCurrency\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Currencies", "(\"ConfiguredBudgetCurrency\" IS NULL OR (length(\"ConfiguredBudgetCurrency\") = 3 AND \"ConfiguredBudgetCurrency\" GLOB '[A-Z][A-Z][A-Z]')) AND (\"MatchedPriceCurrency\" IS NULL OR (length(\"MatchedPriceCurrency\") = 3 AND \"MatchedPriceCurrency\" GLOB '[A-Z][A-Z][A-Z]'))");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Origin", "\"EvidenceOrigin\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Required", "length(\"CriteriaFingerprint\") BETWEEN 1 AND 128 AND length(\"EvidenceKey\") BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.FavouriteCruiseShipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "ShipName")
                        .IsUnique()
                        .HasDatabaseName("UX_FavouriteCruiseShips_Operator_Ship");

                    b.ToTable("FavouriteCruiseShips", null, t =>
                        {
                            t.HasCheckConstraint("CK_FavouriteCruiseShips_Operator_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_FavouriteCruiseShips_Ship_Length", "length(\"ShipName\") BETWEEN 1 AND 500");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.SavedCruiseCriteriaEvaluationStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriteriaFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceTime")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("EvidenceTimeUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "ShipName", "DepartureDate", "DurationNights", "CriteriaFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_SavedCriteriaStates_Sailing_Fingerprint");

                    b.ToTable("SavedCruiseCriteriaEvaluationStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_SavedCriteriaStates_Duration", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_SavedCriteriaStates_Required", "length(\"OperatorId\") BETWEEN 1 AND 200 AND length(\"ShipName\") BETWEEN 1 AND 500 AND length(\"CriteriaFingerprint\") BETWEEN 1 AND 128 AND length(\"EvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCriteriaStates_Result", "\"Result\" BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.SavedCruiseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DisplayedPriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayedPriceBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayedPriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterestLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItineraryRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItinerarySummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetailSourceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShipRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValueRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "ShipName", "DepartureDate", "DurationNights")
                        .IsUnique()
                        .HasDatabaseName("UX_SavedCruises_Sailing");

                    b.ToTable("SavedCruises", null, t =>
                        {
                            t.HasCheckConstraint("CK_SavedCruises_Currency", "length(\"DisplayedPriceCurrency\") = 3 AND \"DisplayedPriceCurrency\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_SavedCruises_DeparturePort_Length", "\"DeparturePort\" IS NULL OR length(\"DeparturePort\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_DisplayedPriceBasis_Length", "\"DisplayedPriceBasis\" IS NULL OR length(\"DisplayedPriceBasis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_Duration", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_SavedCruises_Interest", "\"InterestLevel\" IS NULL OR \"InterestLevel\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_SavedCruises_ItineraryRating", "\"ItineraryRating\" IS NULL OR \"ItineraryRating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SavedCruises_ItinerarySummary_Length", "\"ItinerarySummary\" IS NULL OR length(\"ItinerarySummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCruises_Notes_Length", "\"Notes\" IS NULL OR length(\"Notes\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCruises_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_SavedCruises_OperatorName_Length", "length(\"OperatorName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_OverallRating", "\"OverallRating\" IS NULL OR \"OverallRating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SavedCruises_Price", "CAST(\"DisplayedPriceAmount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_SavedCruises_RetailSourceId_Length", "\"RetailSourceId\" IS NULL OR length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_SavedCruises_RetailSourceName_Length", "\"RetailSourceName\" IS NULL OR length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_ShipName_Length", "length(\"ShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_ShipRating", "\"ShipRating\" IS NULL OR \"ShipRating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SavedCruises_SourcePair", "(\"RetailSourceId\" IS NULL AND \"RetailSourceName\" IS NULL) OR (\"RetailSourceId\" IS NOT NULL AND \"RetailSourceName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_SavedCruises_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCruises_Status", "\"Status\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_SavedCruises_Title_Length", "length(\"Title\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_SavedCruises_ValueRating", "\"ValueRating\" IS NULL OR \"ValueRating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", "History")
                        .WithMany("Observations")
                        .HasForeignKey("CruiseHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("History");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationPriceEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", "Observation")
                        .WithMany("Prices")
                        .HasForeignKey("CruiseObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceCabinEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", "Profile")
                        .WithMany("Cabins")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceMonthEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", "Profile")
                        .WithMany("Months")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePriceDropAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("PriceDropDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruisePriceDropAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePromotionAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("PromotionDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruisePromotionAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("SavedCriteriaDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", b =>
                {
                    b.Navigation("PriceDropDetails");

                    b.Navigation("PromotionDetails");

                    b.Navigation("SavedCriteriaDetails");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", b =>
                {
                    b.Navigation("Cabins");

                    b.Navigation("Months");
                });
#pragma warning restore 612, 618
        }
    }
}
