// <auto-generated />
using System;
using KrytenAssist.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrytenAssist.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KrytenAssistDbContext))]
    [Migration("20260717090431_HardenCruiseHistoryRecording")]
    partial class HardenCruiseHistoryRecording
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KrytenAssist.Core.Entities.PromptCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptCards");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestEvidenceObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestProviderOfferId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestSourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "NormalizedShipName", "DepartureDate", "DurationNights", "RetailSourceId")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseHistories_Sailing_Source");

                    b.ToTable("CruiseHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseHistories_DurationNights", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseHistories_LatestProviderOfferId_Length", "length(\"LatestProviderOfferId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseHistories_LatestSourceReference_Length", "\"LatestSourceReference\" IS NULL OR length(\"LatestSourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseHistories_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseHistories_ShipName_Length", "length(\"NormalizedShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseHistories_SourceId_Length", "length(\"RetailSourceId\") <= 200");

                            t.HasCheckConstraint("CK_CruiseHistories_SourceName_Length", "\"RetailSourceName\" IS NULL OR length(\"RetailSourceName\") BETWEEN 1 AND 500");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItinerarySummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOfferId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CruiseHistoryId", "Fingerprint")
                        .HasDatabaseName("IX_CruiseObservations_History_Fingerprint");

                    b.HasIndex("CruiseHistoryId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseObservations_History_Sequence");

                    b.HasIndex("CruiseHistoryId", "ObservedAt", "Id")
                        .HasDatabaseName("IX_CruiseObservations_History_ObservedAt");

                    b.ToTable("CruiseObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseObservations_DeparturePort_Length", "\"DeparturePort\" IS NULL OR length(\"DeparturePort\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_DurationNights", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseObservations_Fingerprint_Length", "length(\"Fingerprint\") BETWEEN 1 AND 16000");

                            t.HasCheckConstraint("CK_CruiseObservations_ItinerarySummary_Length", "\"ItinerarySummary\" IS NULL OR length(\"ItinerarySummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_OperatorName_Length", "length(\"OperatorName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_PromotionSummary_Length", "\"PromotionSummary\" IS NULL OR length(\"PromotionSummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_ProviderOfferId_Length", "length(\"ProviderOfferId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseObservations_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_CruiseObservations_ShipName_Length", "length(\"ShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_Title_Length", "length(\"Title\") BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationPriceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Basis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CruiseObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseObservationId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseObservationPrices_Observation_Order");

                    b.ToTable("CruiseObservationPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseObservationPrices_Amount", "CAST(\"Amount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_Basis_Length", "\"Basis\" IS NULL OR length(\"Basis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_Currency", "length(\"Currency\") = 3 AND \"Currency\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_DisplayOrder", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", "History")
                        .WithMany("Observations")
                        .HasForeignKey("CruiseHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("History");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationPriceEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", "Observation")
                        .WithMany("Prices")
                        .HasForeignKey("CruiseObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
