// <auto-generated />
using System;
using KrytenAssist.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrytenAssist.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KrytenAssistDbContext))]
    [Migration("20260720185813_AddNewItineraryAlertIntegration")]
    partial class AddNewItineraryAlertIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KrytenAssist.Core.Entities.PromptCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PromptCards");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTime")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("EventTimeUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItineraryOperatorId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderItineraryId")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseAlerts_EventKey");

                    b.HasIndex("EventTimeUtcTicks", "CreatedAtUtcTicks", "EventKey")
                        .HasDatabaseName("IX_CruiseAlerts_Newest");

                    b.HasIndex("Status", "Type", "EventTimeUtcTicks")
                        .HasDatabaseName("IX_CruiseAlerts_Status_Type_Event");

                    b.ToTable("CruiseAlerts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseAlerts_EventKey", "length(\"EventKey\") = 64 AND \"EventKey\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseAlerts_ItineraryOperatorId_Length", "\"ItineraryOperatorId\" IS NULL OR length(\"ItineraryOperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseAlerts_OperatorId_Length", "\"OperatorId\" IS NULL OR length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseAlerts_ProviderItineraryId_Length", "\"ProviderItineraryId\" IS NULL OR length(\"ProviderItineraryId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseAlerts_RetailSourceId_Length", "\"RetailSourceId\" IS NULL OR length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseAlerts_RetailSourceName_Length", "\"RetailSourceName\" IS NULL OR length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseAlerts_ShipName_Length", "\"ShipName\" IS NULL OR length(\"ShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseAlerts_SourcePair", "(\"RetailSourceId\" IS NULL AND \"RetailSourceName\" IS NULL) OR (\"RetailSourceId\" IS NOT NULL AND \"RetailSourceName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruiseAlerts_Status", "\"Status\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_CruiseAlerts_Subject", "(\"Type\" BETWEEN 0 AND 3 AND \"OperatorId\" IS NOT NULL AND \"ShipName\" IS NOT NULL AND \"DepartureDate\" IS NOT NULL AND \"DurationNights\" > 0 AND \"ItineraryOperatorId\" IS NULL AND \"ProviderItineraryId\" IS NULL) OR (\"Type\" = 4 AND \"OperatorId\" IS NULL AND \"ShipName\" IS NULL AND \"DepartureDate\" IS NULL AND \"DurationNights\" IS NULL AND \"ItineraryOperatorId\" IS NOT NULL AND \"ProviderItineraryId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruiseAlerts_Type", "\"Type\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_CruiseAlerts_TypeSource", "(\"Type\" IN (0, 1, 3, 4) AND \"RetailSourceId\" IS NOT NULL) OR (\"Type\" = 2 AND \"RetailSourceId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseAlertSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CabinAvailabilityEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("MinimumPriceDropPercentage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NewItineraryEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PriceDropEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromotionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SavedCriteriaEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CruiseAlertSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseAlertSettings_Booleans", "\"PriceDropEnabled\" IN (0,1) AND \"PromotionEnabled\" IN (0,1) AND \"SavedCriteriaEnabled\" IN (0,1) AND \"CabinAvailabilityEnabled\" IN (0,1) AND \"NewItineraryEnabled\" IN (0,1)");

                            t.HasCheckConstraint("CK_CruiseAlertSettings_Percentage", "CAST(\"MinimumPriceDropPercentage\" AS REAL) BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_CruiseAlertSettings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinAvailabilityAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CabinType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Coverage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceTime")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruiseCabinAvailabilityAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseCabinAvailabilityDetails_CabinType", "\"CabinType\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_CruiseCabinAvailabilityDetails_ContextFingerprint", "length(\"ContextFingerprint\") = 64 AND \"ContextFingerprint\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseCabinAvailabilityDetails_Coverage", "\"Coverage\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruiseCabinAvailabilityDetails_EvidenceKey", "length(\"EvidenceKey\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseCabinAvailabilityDetails_StateFingerprint", "length(\"StateFingerprint\") = 64 AND \"StateFingerprint\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseCabinAvailabilityDetails_Transition", "(\"PreviousState\" = 2 AND \"CurrentState\" = 1 AND \"Direction\" = 0) OR (\"PreviousState\" = 1 AND \"CurrentState\" = 2 AND \"Direction\" = 1)");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinContextChildAgeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseCabinSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseCabinSeriesId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseCabinContextChildAges_Series_Order");

                    b.ToTable("CruiseCabinContextChildAges", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseCabinContextChildAges_Age", "\"Age\" BETWEEN 0 AND 17");

                            t.HasCheckConstraint("CK_CruiseCabinContextChildAges_Order", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coverage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseCabinSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CruiseCabinSeriesId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseCabinObservations_Series_Sequence");

                    b.HasIndex("CruiseCabinSeriesId", "StateFingerprint")
                        .HasDatabaseName("IX_CruiseCabinObservations_Series_State");

                    b.HasIndex("CruiseCabinSeriesId", "ObservedAtUtcTicks", "StateFingerprint")
                        .HasDatabaseName("IX_CruiseCabinObservations_Series_Observed");

                    b.ToTable("CruiseCabinObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseCabinObservations_Coverage", "\"Coverage\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruiseCabinObservations_EvidenceKey_Length", "length(\"EvidenceKey\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseCabinObservations_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_CruiseCabinObservations_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseCabinObservations_StateFingerprint", "length(\"StateFingerprint\") = 64 AND \"StateFingerprint\" NOT GLOB '*[^0-9a-f]*'");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinObservationStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CabinType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseCabinObservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseCabinObservationId", "CabinType")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseCabinObservationStates_Observation_Cabin");

                    b.ToTable("CruiseCabinObservationStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseCabinObservationStates_Availability", "\"Availability\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_CruiseCabinObservationStates_CabinType", "\"CabinType\" BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinSeriesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdultCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CabinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChildAgesKnown")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChildCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureAirportId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstObservedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestEvidenceKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestEvidenceObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("LatestEvidenceObservedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestSourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetailSourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseCabinSeries_SeriesKey");

                    b.HasIndex("DepartureDate", "OperatorId", "ShipName", "RetailSourceId", "ContextFingerprint")
                        .HasDatabaseName("IX_CruiseCabinSeries_List");

                    b.ToTable("CruiseCabinSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseCabinSeries_Adults", "\"AdultCount\" IS NULL OR \"AdultCount\" BETWEEN 0 AND 32");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_CabinQuantity", "\"CabinQuantity\" IS NULL OR \"CabinQuantity\" BETWEEN 1 AND 16");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_ChildAgesKnown", "\"ChildAgesKnown\" IN (0,1)");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_Children", "\"ChildCount\" IS NULL OR \"ChildCount\" BETWEEN 0 AND 32");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_ContextFingerprint", "length(\"ContextFingerprint\") = 64 AND \"ContextFingerprint\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_DepartureAirportId_Length", "\"DepartureAirportId\" IS NULL OR length(\"DepartureAirportId\") BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_Duration", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_LatestEvidenceKey_Length", "length(\"LatestEvidenceKey\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_LatestSourceReference_Length", "\"LatestSourceReference\" IS NULL OR length(\"LatestSourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_PackageMode", "\"PackageMode\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_RetailSourceId_Length", "length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_RetailSourceName_Length", "length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_SeriesKey", "length(\"SeriesKey\") = 64 AND \"SeriesKey\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseCabinSeries_ShipName_Length", "length(\"ShipName\") BETWEEN 1 AND 500");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryCheckEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseDiscoveryScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasTruncated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDiscoveryScopeId");

                    b.HasIndex("EvidenceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseDiscoveryChecks_EvidenceKey");

                    b.HasIndex("ObservedAtUtcTicks", "EvidenceKey")
                        .HasDatabaseName("IX_CruiseDiscoveryChecks_Observed");

                    b.ToTable("CruiseDiscoveryChecks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseDiscoveryCheckEntity_EvidenceKey", "length(\"EvidenceKey\") = 64 AND \"EvidenceKey\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseDiscoveryChecks_Accepted", "\"AcceptedCount\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_CruiseDiscoveryChecks_Rejected", "\"RejectedCount\" BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_CruiseDiscoveryChecks_Truncated", "\"WasTruncated\" IN (0,1)");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryOccurrenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogueKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CruiseDiscoveryCheckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItinerarySummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccurrenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderItineraryId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOfferId")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDiscoveryCheckId", "CatalogueKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseDiscoveryOccurrences_Check_Catalogue");

                    b.HasIndex("CatalogueKey", "ObservedAtUtcTicks", "OccurrenceFingerprint")
                        .HasDatabaseName("IX_CruiseDiscoveryOccurrences_Catalogue_Observed");

                    b.ToTable("CruiseDiscoveryOccurrences", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_CatalogueKey", "length(\"CatalogueKey\") = 64 AND \"CatalogueKey\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_DeparturePort_Length", "\"DeparturePort\" IS NULL OR length(\"DeparturePort\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_EvidenceKey_Length", "length(\"EvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_ItinerarySummary_Length", "\"ItinerarySummary\" IS NULL OR length(\"ItinerarySummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_OccurrenceFingerprint", "length(\"OccurrenceFingerprint\") = 64 AND \"OccurrenceFingerprint\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_ProviderItineraryId_Length", "length(\"ProviderItineraryId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_ProviderOfferId_Length", "\"ProviderOfferId\" IS NULL OR length(\"ProviderOfferId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_RetailSourceId_Length", "length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_RetailSourceName_Length", "length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_ShipName_Length", "\"ShipName\" IS NULL OR length(\"ShipName\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrenceEntity_Title_Length", "\"Title\" IS NULL OR length(\"Title\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryOccurrences_Duration", "\"DurationNights\" IS NULL OR \"DurationNights\" BETWEEN 1 AND 365");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryRejectionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidateKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CruiseDiscoveryCheckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDiscoveryCheckId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseDiscoveryRejections_Check_Order");

                    b.ToTable("CruiseDiscoveryRejections", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseDiscoveryRejectionEntity_CandidateKey_Length", "length(\"CandidateKey\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryRejectionEntity_Reason_Length", "length(\"Reason\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseDiscoveryRejections_Order", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeCriterionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseDiscoveryScopeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDiscoveryScopeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseDiscoveryScopeCriteria_Scope_Name");

                    b.ToTable("CruiseDiscoveryScopeCriteria", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeCriteria_State", "\"State\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeCriterionEntity_Name_Length", "length(\"Name\") BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeCriterionValueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseDiscoveryScopeCriterionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDiscoveryScopeCriterionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseDiscoveryScopeCriterionValues_Criterion_Order");

                    b.HasIndex("CruiseDiscoveryScopeCriterionId", "Value")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseDiscoveryScopeCriterionValues_Criterion_Value");

                    b.ToTable("CruiseDiscoveryScopeCriterionValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeCriterionValueEntity_Value_Length", "length(\"Value\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeCriterionValues_Order", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureContractVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstCheckedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstCheckedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCheckedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastCheckedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Surface")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScopeFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseDiscoveryScopes_Fingerprint");

                    b.HasIndex("LastCheckedAtUtcTicks", "ScopeFingerprint")
                        .HasDatabaseName("IX_CruiseDiscoveryScopes_LastCheck");

                    b.ToTable("CruiseDiscoveryScopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeEntity_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeEntity_RetailSourceId_Length", "length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeEntity_RetailSourceName_Length", "length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopeEntity_ScopeFingerprint", "length(\"ScopeFingerprint\") = 64 AND \"ScopeFingerprint\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopes_Surface", "\"Surface\" = 0");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopes_Time", "\"FirstCheckedAtUtcTicks\" <= \"LastCheckedAtUtcTicks\"");

                            t.HasCheckConstraint("CK_CruiseDiscoveryScopes_Version", "\"CaptureContractVersion\" BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestEvidenceObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestProviderOfferId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestSourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "NormalizedShipName", "DepartureDate", "DurationNights", "RetailSourceId")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseHistories_Sailing_Source");

                    b.ToTable("CruiseHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseHistories_DurationNights", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseHistories_LatestProviderOfferId_Length", "length(\"LatestProviderOfferId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseHistories_LatestSourceReference_Length", "\"LatestSourceReference\" IS NULL OR length(\"LatestSourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseHistories_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseHistories_ShipName_Length", "length(\"NormalizedShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseHistories_SourceId_Length", "length(\"RetailSourceId\") <= 200");

                            t.HasCheckConstraint("CK_CruiseHistories_SourceName_Length", "\"RetailSourceName\" IS NULL OR length(\"RetailSourceName\") BETWEEN 1 AND 500");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseItineraryCatalogueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogueKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstObservedEventKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstOccurrenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LatestOccurrenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderItineraryId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseItineraryCatalogue_Key");

                    b.HasIndex("FirstObservedEventKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseItineraryCatalogue_EventKey")
                        .HasFilter("\"FirstObservedEventKey\" IS NOT NULL");

                    b.HasIndex("FirstOccurrenceId");

                    b.HasIndex("LatestOccurrenceId");

                    b.HasIndex("FirstSeenAtUtcTicks", "CatalogueKey")
                        .HasDatabaseName("IX_CruiseItineraryCatalogue_FirstSeen");

                    b.ToTable("CruiseItineraryCatalogue", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseItineraryCatalogueEntity_CatalogueKey", "length(\"CatalogueKey\") = 64 AND \"CatalogueKey\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseItineraryCatalogueEntity_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseItineraryCatalogueEntity_ProviderItineraryId_Length", "length(\"ProviderItineraryId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseItineraryCatalogueEntity_RetailSourceId_Length", "length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseItineraryCatalogueEntity_RetailSourceName_Length", "length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseItineraryCatalogue_EventKey", "\"FirstObservedEventKey\" IS NULL OR (length(\"FirstObservedEventKey\") = 64 AND \"FirstObservedEventKey\" NOT GLOB '*[^0-9a-f]*')");

                            t.HasCheckConstraint("CK_CruiseItineraryCatalogue_Time", "\"FirstSeenAtUtcTicks\" <= \"LastSeenAtUtcTicks\"");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseNewItineraryAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckEvidenceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstObservedEventKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItinerarySummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurrenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderItineraryId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruiseNewItineraryAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_DeparturePort_Length", "\"DeparturePort\" IS NULL OR length(\"DeparturePort\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_Duration", "\"DurationNights\" IS NULL OR \"DurationNights\" BETWEEN 1 AND 365");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_Hashes", "length(\"ScopeFingerprint\") = 64 AND \"ScopeFingerprint\" NOT GLOB '*[^0-9a-f]*' AND length(\"CheckEvidenceKey\") = 64 AND \"CheckEvidenceKey\" NOT GLOB '*[^0-9a-f]*' AND length(\"OccurrenceFingerprint\") = 64 AND \"OccurrenceFingerprint\" NOT GLOB '*[^0-9a-f]*' AND length(\"FirstObservedEventKey\") = 64 AND \"FirstObservedEventKey\" NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_ItinerarySummary_Length", "\"ItinerarySummary\" IS NULL OR length(\"ItinerarySummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_ProviderEvidenceKey_Length", "length(\"ProviderEvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_ProviderItineraryId_Length", "length(\"ProviderItineraryId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_ShipName_Length", "\"ShipName\" IS NULL OR length(\"ShipName\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseNewItineraryDetails_Title_Length", "\"Title\" IS NULL OR length(\"Title\") BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CruiseHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItinerarySummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOfferId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CruiseHistoryId", "Fingerprint")
                        .HasDatabaseName("IX_CruiseObservations_History_Fingerprint");

                    b.HasIndex("CruiseHistoryId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseObservations_History_Sequence");

                    b.HasIndex("CruiseHistoryId", "ObservedAt", "Id")
                        .HasDatabaseName("IX_CruiseObservations_History_ObservedAt");

                    b.ToTable("CruiseObservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseObservations_DeparturePort_Length", "\"DeparturePort\" IS NULL OR length(\"DeparturePort\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_DurationNights", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_CruiseObservations_Fingerprint_Length", "length(\"Fingerprint\") BETWEEN 1 AND 16000");

                            t.HasCheckConstraint("CK_CruiseObservations_ItinerarySummary_Length", "\"ItinerarySummary\" IS NULL OR length(\"ItinerarySummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_OperatorName_Length", "length(\"OperatorName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_PromotionSummary_Length", "\"PromotionSummary\" IS NULL OR length(\"PromotionSummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_ProviderOfferId_Length", "length(\"ProviderOfferId\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_CruiseObservations_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_CruiseObservations_ShipName_Length", "length(\"ShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservations_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruiseObservations_Title_Length", "length(\"Title\") BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationPriceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Basis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CruiseObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseObservationId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseObservationPrices_Observation_Order");

                    b.ToTable("CruiseObservationPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseObservationPrices_Amount", "CAST(\"Amount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_Basis_Length", "\"Basis\" IS NULL OR length(\"Basis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_Currency", "length(\"Currency\") = 3 AND \"Currency\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_CruiseObservationPrices_DisplayOrder", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceCabinEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cabin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Cabin")
                        .IsUnique()
                        .HasDatabaseName("UX_CruisePreferenceCabins_Profile_Cabin");

                    b.ToTable("CruisePreferenceCabins", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePreferenceCabins_Cabin", "\"Cabin\" BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceMonthEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Month")
                        .IsUnique()
                        .HasDatabaseName("UX_CruisePreferenceMonths_Profile_Month");

                    b.ToTable("CruisePreferenceMonths", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePreferenceMonths_Month", "\"Month\" BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaximumBudgetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximumBudgetBasis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaximumBudgetCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CruisePreferenceProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetAmount", "\"MaximumBudgetAmount\" IS NULL OR CAST(\"MaximumBudgetAmount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetBasis", "\"MaximumBudgetBasis\" IS NULL OR \"MaximumBudgetBasis\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetCurrency", "\"MaximumBudgetCurrency\" IS NULL OR (length(\"MaximumBudgetCurrency\") = 3 AND \"MaximumBudgetCurrency\" GLOB '[A-Z][A-Z][A-Z]')");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_BudgetTuple", "(\"MaximumBudgetAmount\" IS NULL AND \"MaximumBudgetCurrency\" IS NULL AND \"MaximumBudgetBasis\" IS NULL) OR (\"MaximumBudgetAmount\" IS NOT NULL AND \"MaximumBudgetCurrency\" IS NOT NULL AND \"MaximumBudgetBasis\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruisePreferenceProfiles_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePriceDropAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentAmount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PercentageReduction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousAmount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reduction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruisePriceDropAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePriceDropDetails_Amounts", "CAST(\"PreviousAmount\" AS REAL) >= 0 AND CAST(\"CurrentAmount\" AS REAL) >= 0 AND CAST(\"Reduction\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_CurrentBasis_Length", "\"CurrentBasis\" IS NULL OR length(\"CurrentBasis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_CurrentCurrency", "length(\"CurrentCurrency\") = 3 AND \"CurrentCurrency\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_EvidenceKey_Length", "length(\"EvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_Percentage", "CAST(\"PercentageReduction\" AS REAL) BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_PreviousBasis_Length", "\"PreviousBasis\" IS NULL OR length(\"PreviousBasis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruisePriceDropDetails_PreviousCurrency", "length(\"PreviousCurrency\") = 3 AND \"PreviousCurrency\" GLOB '[A-Z][A-Z][A-Z]'");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePromotionAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruisePromotionAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruisePromotionDetails_CurrentSummary_Length", "length(\"CurrentSummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruisePromotionDetails_EvidenceKey_Length", "length(\"EvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_CruisePromotionDetails_PreviousSummary_Length", "\"PreviousSummary\" IS NULL OR length(\"PreviousSummary\") BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertCabinEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CabinType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CruiseAlertId", "CabinType")
                        .IsUnique()
                        .HasDatabaseName("UX_CruiseSavedCriteriaAlertCabins_Alert_Cabin");

                    b.ToTable("CruiseSavedCriteriaAlertCabins", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseSavedCriteriaAlertCabins_CabinType", "\"CabinType\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaAlertCabins_IsMatched", "\"IsMatched\" IN (0,1)");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", b =>
                {
                    b.Property<Guid>("CruiseAlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinContextFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CabinCriterionResult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CabinEvidenceKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinEvidenceTime")
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CabinPreferencesUnavailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfiguredBudgetAmount")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfiguredBudgetBasis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfiguredBudgetCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceTime")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedPriceAmount")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedPriceBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedPriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MonthConfiguredAndMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("CruiseAlertId");

                    b.ToTable("CruiseSavedCriteriaAlertDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Amounts", "(\"ConfiguredBudgetAmount\" IS NULL OR CAST(\"ConfiguredBudgetAmount\" AS REAL) >= 0) AND (\"MatchedPriceAmount\" IS NULL OR CAST(\"MatchedPriceAmount\" AS REAL) >= 0)");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Booleans", "\"MonthConfiguredAndMatched\" IN (0,1) AND \"CabinPreferencesUnavailable\" IN (0,1)");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_BudgetBasis", "\"ConfiguredBudgetBasis\" IS NULL OR \"ConfiguredBudgetBasis\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_BudgetTuple", "(\"ConfiguredBudgetAmount\" IS NULL AND \"ConfiguredBudgetCurrency\" IS NULL AND \"ConfiguredBudgetBasis\" IS NULL AND \"MatchedPriceAmount\" IS NULL AND \"MatchedPriceCurrency\" IS NULL AND \"MatchedPriceBasis\" IS NULL) OR (\"ConfiguredBudgetAmount\" IS NOT NULL AND \"ConfiguredBudgetCurrency\" IS NOT NULL AND \"ConfiguredBudgetBasis\" IS NOT NULL AND \"MatchedPriceAmount\" IS NOT NULL AND \"MatchedPriceCurrency\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_CabinContext", "\"CabinContextFingerprint\" IS NULL OR (length(\"CabinContextFingerprint\") = 64 AND \"CabinContextFingerprint\" NOT GLOB '*[^0-9a-f]*')");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_CabinEvidence", "(\"CabinEvidenceKey\" IS NULL AND \"CabinEvidenceTime\" IS NULL) OR (\"CabinEvidenceKey\" IS NOT NULL AND \"CabinEvidenceTime\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_CabinEvidenceKey", "\"CabinEvidenceKey\" IS NULL OR length(\"CabinEvidenceKey\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_CabinResult", "\"CabinCriterionResult\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Currencies", "(\"ConfiguredBudgetCurrency\" IS NULL OR (length(\"ConfiguredBudgetCurrency\") = 3 AND \"ConfiguredBudgetCurrency\" GLOB '[A-Z][A-Z][A-Z]')) AND (\"MatchedPriceCurrency\" IS NULL OR (length(\"MatchedPriceCurrency\") = 3 AND \"MatchedPriceCurrency\" GLOB '[A-Z][A-Z][A-Z]'))");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Origin", "\"EvidenceOrigin\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CruiseSavedCriteriaDetails_Required", "length(\"CriteriaFingerprint\") BETWEEN 1 AND 128 AND length(\"EvidenceKey\") BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.FavouriteCruiseShipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "ShipName")
                        .IsUnique()
                        .HasDatabaseName("UX_FavouriteCruiseShips_Operator_Ship");

                    b.ToTable("FavouriteCruiseShips", null, t =>
                        {
                            t.HasCheckConstraint("CK_FavouriteCruiseShips_Operator_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_FavouriteCruiseShips_Ship_Length", "length(\"ShipName\") BETWEEN 1 AND 500");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.SavedCruiseCriteriaEvaluationStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriteriaFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceTime")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<long>("EvidenceTimeUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "ShipName", "DepartureDate", "DurationNights", "CriteriaFingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_SavedCriteriaStates_Sailing_Fingerprint");

                    b.ToTable("SavedCruiseCriteriaEvaluationStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_SavedCriteriaStates_Duration", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_SavedCriteriaStates_Required", "length(\"OperatorId\") BETWEEN 1 AND 200 AND length(\"ShipName\") BETWEEN 1 AND 500 AND length(\"CriteriaFingerprint\") BETWEEN 1 AND 128 AND length(\"EvidenceKey\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCriteriaStates_Result", "\"Result\" BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.SavedCruiseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DisplayedPriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayedPriceBasis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayedPriceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationNights")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterestLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItineraryRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItinerarySummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetailSourceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetailSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedAt")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShipRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValueRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "ShipName", "DepartureDate", "DurationNights")
                        .IsUnique()
                        .HasDatabaseName("UX_SavedCruises_Sailing");

                    b.ToTable("SavedCruises", null, t =>
                        {
                            t.HasCheckConstraint("CK_SavedCruises_Currency", "length(\"DisplayedPriceCurrency\") = 3 AND \"DisplayedPriceCurrency\" GLOB '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_SavedCruises_DeparturePort_Length", "\"DeparturePort\" IS NULL OR length(\"DeparturePort\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_DisplayedPriceBasis_Length", "\"DisplayedPriceBasis\" IS NULL OR length(\"DisplayedPriceBasis\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_Duration", "\"DurationNights\" > 0");

                            t.HasCheckConstraint("CK_SavedCruises_Interest", "\"InterestLevel\" IS NULL OR \"InterestLevel\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_SavedCruises_ItineraryRating", "\"ItineraryRating\" IS NULL OR \"ItineraryRating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SavedCruises_ItinerarySummary_Length", "\"ItinerarySummary\" IS NULL OR length(\"ItinerarySummary\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCruises_Notes_Length", "\"Notes\" IS NULL OR length(\"Notes\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCruises_OperatorId_Length", "length(\"OperatorId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_SavedCruises_OperatorName_Length", "length(\"OperatorName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_OverallRating", "\"OverallRating\" IS NULL OR \"OverallRating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SavedCruises_Price", "CAST(\"DisplayedPriceAmount\" AS REAL) >= 0");

                            t.HasCheckConstraint("CK_SavedCruises_RetailSourceId_Length", "\"RetailSourceId\" IS NULL OR length(\"RetailSourceId\") BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_SavedCruises_RetailSourceName_Length", "\"RetailSourceName\" IS NULL OR length(\"RetailSourceName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_ShipName_Length", "length(\"ShipName\") BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_SavedCruises_ShipRating", "\"ShipRating\" IS NULL OR \"ShipRating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SavedCruises_SourcePair", "(\"RetailSourceId\" IS NULL AND \"RetailSourceName\" IS NULL) OR (\"RetailSourceId\" IS NOT NULL AND \"RetailSourceName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_SavedCruises_SourceReference_Length", "\"SourceReference\" IS NULL OR length(\"SourceReference\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_SavedCruises_Status", "\"Status\" BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_SavedCruises_Title_Length", "length(\"Title\") BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_SavedCruises_ValueRating", "\"ValueRating\" IS NULL OR \"ValueRating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinAvailabilityAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("CabinAvailabilityDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruiseCabinAvailabilityAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinContextChildAgeEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseCabinSeriesEntity", "Series")
                        .WithMany("ChildAges")
                        .HasForeignKey("CruiseCabinSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinObservationEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseCabinSeriesEntity", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("CruiseCabinSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinObservationStateEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseCabinObservationEntity", "Observation")
                        .WithMany("States")
                        .HasForeignKey("CruiseCabinObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryCheckEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeEntity", "Scope")
                        .WithMany("Checks")
                        .HasForeignKey("CruiseDiscoveryScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryOccurrenceEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryCheckEntity", "Check")
                        .WithMany("Occurrences")
                        .HasForeignKey("CruiseDiscoveryCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryRejectionEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryCheckEntity", "Check")
                        .WithMany("Rejections")
                        .HasForeignKey("CruiseDiscoveryCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeCriterionEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeEntity", "Scope")
                        .WithMany("Criteria")
                        .HasForeignKey("CruiseDiscoveryScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeCriterionValueEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeCriterionEntity", "Criterion")
                        .WithMany("Values")
                        .HasForeignKey("CruiseDiscoveryScopeCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseItineraryCatalogueEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryOccurrenceEntity", "FirstOccurrence")
                        .WithMany()
                        .HasForeignKey("FirstOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryOccurrenceEntity", "LatestOccurrence")
                        .WithMany()
                        .HasForeignKey("LatestOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstOccurrence");

                    b.Navigation("LatestOccurrence");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseNewItineraryAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("NewItineraryDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruiseNewItineraryAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", "History")
                        .WithMany("Observations")
                        .HasForeignKey("CruiseHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("History");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationPriceEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", "Observation")
                        .WithMany("Prices")
                        .HasForeignKey("CruiseObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceCabinEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", "Profile")
                        .WithMany("Cabins")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceMonthEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", "Profile")
                        .WithMany("Months")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePriceDropAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("PriceDropDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruisePriceDropAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePromotionAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("PromotionDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruisePromotionAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertCabinEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", "Details")
                        .WithMany("Cabins")
                        .HasForeignKey("CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Details");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", b =>
                {
                    b.HasOne("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", "Alert")
                        .WithOne("SavedCriteriaDetails")
                        .HasForeignKey("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", "CruiseAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseAlertEntity", b =>
                {
                    b.Navigation("CabinAvailabilityDetails");

                    b.Navigation("NewItineraryDetails");

                    b.Navigation("PriceDropDetails");

                    b.Navigation("PromotionDetails");

                    b.Navigation("SavedCriteriaDetails");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinObservationEntity", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseCabinSeriesEntity", b =>
                {
                    b.Navigation("ChildAges");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryCheckEntity", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("Rejections");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeCriterionEntity", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseDiscoveryScopeEntity", b =>
                {
                    b.Navigation("Checks");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseHistoryEntity", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseObservationEntity", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruisePreferenceProfileEntity", b =>
                {
                    b.Navigation("Cabins");

                    b.Navigation("Months");
                });

            modelBuilder.Entity("KrytenAssist.Infrastructure.Persistence.CruiseSavedCriteriaAlertDetailEntity", b =>
                {
                    b.Navigation("Cabins");
                });
#pragma warning restore 612, 618
        }
    }
}
